package com.postagging.postagger.crf.features;

import java.awt.event.MouseWheelEvent;
import java.util.LinkedHashSet;
import java.util.Set;

import com.crf.filters.Filter;
import com.crf.filters.FilterFactory;
import com.crf.filters.TwoTagsFilter;

/**
 *  A {@link FilterFactory} for the features generated by the {@link StandardFeatureGenerator}.
 * @author 1001937
 *
 */
public class StandardFilterFactory implements FilterFactory<String, String> {

	@Override
	public Set<Filter<String, String>> createFilters(String[] sequence, int tokenIndex, String currentTag,
			String previousTag) {
		String token = sequence[tokenIndex];
		Set<Filter<String, String>> ret = new LinkedHashSet<Filter<String, String>>();
		ret.add(new TwoTagsFilter<String, String>(currentTag, previousTag));
		ret.add(new CaseInsensitiveTokenAndTagFilter(token, currentTag));
		return ret;
	}
}
